services:
  hexo:
    image: hexo.blog.piprime.fr:latest
    build:
      context: hexo
      target: builder
  caddy:
    image: caddy.blog.piprime.fr:latest
    build: ./caddy

  dev:
    image: hexo.blog.piprime.fr:latest
    depends_on:
      - hexo
    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    profiles:
      - dev
    environment:
      SERVER_PORT: ${SERVER_PORT}
    command: "make dev"
    volumes:
      - ./hexo:/hexo:rw

  clean:
    image: hexo.blog.piprime.fr:latest
    depends_on:
      - hexo
    command: "make clean"
    volumes:
      - ./hexo:/hexo:rw

  deploy-hexo:
    image: hexo.blog.piprime.fr:latest
    depends_on:
      - hexo
    profiles:
      - production
    command: "make deploy"
    volumes:
      - ./hexo:/hexo:rw

  deploy:
    image: caddy.blog.piprime.fr:latest
    depends_on:
      - deploy-hexo
      - caddy
    volumes:
      - ./hexo/public:/srv:ro
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
